<h4><?php echo $this->__('Processing order.') ?></h4>
<form id="processpayment" method="post" action="#" >

<div id="display_output"></div>

<input type="hidden" name="payment[method]" value="pos" id="method"/>  
<input type="hidden" value="1" name="amount" id="amount" />
<input type="hidden" value="1" name="success" id="success" />
<?php

require_once("SFAClient/Sfa/EncryptionUtil.php");


		 $strMerchantId="96013917";
		 $astrFileName="96013917.key";
		 $astrClearData;
		 $ResponseCode = "";
		 $Message = "";
		 $TxnID = "";
		 $ePGTxnID = "";
	     $AuthIdCode = "";
		 $RRN = "";
		 $CVRespCode = "";
		 $Reserve1 = "";
		 $Reserve2 = "";
		 $Reserve3 = "";
		 $Reserve4 = "";
		 $Reserve5 = "";
		 $Reserve6 = "";
		 $Reserve7 = "";
		 $Reserve8 = "";
		 $Reserve9 = "";
		 $Reserve10 = "";


		 if($_POST){

			if($_POST['DATA']==null){
				print "null is the value";
			}
			 $astrResponseData=$_POST['DATA'];
			 $astrDigest = $_POST['EncryptedData'];
			 $oEncryptionUtilenc = 	new 	EncryptionUtil();
			 $astrsfaDigest  = $oEncryptionUtilenc->getHMAC($astrResponseData,$astrFileName,$strMerchantId);

			if (strcasecmp($astrDigest, $astrsfaDigest) == 0) {
			 parse_str($astrResponseData, $output);
			 if( array_key_exists('RespCode', $output) == 1) {
			 	$ResponseCode = $output['RespCode'];
			 }
			 if( array_key_exists('Message', $output) == 1) {
			 	$Message = $output['Message'];
			 }
			 if( array_key_exists('TxnID', $output) == 1) {
			 	$TxnID=$output['TxnID'];
			 }
			 if( array_key_exists('ePGTxnID', $output) == 1) {
			 	$ePGTxnID=$output['ePGTxnID'];
			 }
			 if( array_key_exists('AuthIdCode', $output) == 1) {
			 	$AuthIdCode=$output['AuthIdCode'];
			 }
			 if( array_key_exists('RRN', $output) == 1) {
			 	$RRN = $output['RRN'];
			 }
			 if( array_key_exists('CVRespCode', $output) == 1) {
			 	$CVRespCode=$output['CVRespCode'];
			 }
			}
		 }
	print "<h1>Response Code:: $ResponseCode <br>";
	print "<h1>Response Message:: $Message <br>";
	print "<h1>Auth ID Code:: $AuthIdCode <br>";
	print "<h1>RRN:: $RRN<br>";
	print "<h1>Transaction id:: $TxnID<br>";
	print "<h1>Epg Transaction ID:: $ePGTxnID<br>";
	print "<h1>CV Response Code:: $CVRespCode<br>";

$form_key=Mage::getSingleton('core/session')->getFormKey(); 
?>
 <script type="text/javascript">
//<![CDATA[

function ajaxDispay(){
new Ajax.Request('https://cybrainsoftware.com/myshop/checkout/onepage/saveOrder/form_key/<?php echo $form_key;?>', {    
method: 'POST',
parameters: Form.serialize('processpayment'), 
onComplete: function(transport) {
  //alert(transport.responseText);// response from the controller will get alerted.
   document.getElementById("display_output").innerHTML=transport.responseText;
}
});
}
ajaxDispay();
//]]>
</script></form>